@echo off
echo Starting Docker rebuild...
docker compose down -v
echo Building images...
docker compose build --no-cache
echo Starting services...
docker compose up -d
echo Done.
docker compose ps
